status = [
  "build-app",
  "build-website",
  "build-gateway"
]
block_labels = [ "type/do-not-merge" ]
cut_body_after = "<details>"
timeout_sec = 36000
commit_title = "Auto merge of ${PR_REFS}"
delete_merged_branches = true

[committer]
name = "cassandara"
email = "106465547+cassandara@users.noreply.github.com"
