version: "3"

services:
  api:
    container_name: derailed-api
    restart: unless-stopped
    depends_on: [ "gateway", "postgres" ]
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: api/Dockerfile
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:abcefghijklmnopqrswxyz1234567890@localhost:5432

  gateway:
    container_name: derailed-gateway
    restart: unless-stopped
    depends_on: [ "postgres" ]
    ports:
      - "9090:9090"
    build:
      context: .
      dockerfile: gateway/Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:abcefghijklmnopqrswxyz1234567890@localhost:5432

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: abcefghijklmnopqrswxyz1234567890
