# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import auth_pb2 as auth__pb2


class AuthorizationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
        ----
            channel: A grpc.Channel.
        """
        self.create = channel.unary_unary(
            '/derailed.grpc.auth.Authorization/create',
            request_serializer=auth__pb2.CreateToken.SerializeToString,
            response_deserializer=auth__pb2.NewToken.FromString,
        )
        self.validate = channel.unary_unary(
            '/derailed.grpc.auth.Authorization/validate',
            request_serializer=auth__pb2.ValidateToken.SerializeToString,
            response_deserializer=auth__pb2.Valid.FromString,
        )


class AuthorizationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def validate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthorizationServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'create': grpc.unary_unary_rpc_method_handler(
            servicer.create,
            request_deserializer=auth__pb2.CreateToken.FromString,
            response_serializer=auth__pb2.NewToken.SerializeToString,
        ),
        'validate': grpc.unary_unary_rpc_method_handler(
            servicer.validate,
            request_deserializer=auth__pb2.ValidateToken.FromString,
            response_serializer=auth__pb2.Valid.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'derailed.grpc.auth.Authorization', rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class Authorization(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def create(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/derailed.grpc.auth.Authorization/create',
            auth__pb2.CreateToken.SerializeToString,
            auth__pb2.NewToken.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def validate(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/derailed.grpc.auth.Authorization/validate',
            auth__pb2.ValidateToken.SerializeToString,
            auth__pb2.Valid.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
