# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gateway.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rgateway.proto\x12\x10\x64\x65railed.gateway\x1a\x19google/protobuf/any.proto\x1a\x1bgoogle/protobuf/empty.proto"E\n\x0bInterchange\x12\t\n\x01t\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x03\x12\x1f\n\x01\x64\x18\x03 \x01(\x0b\x32\x14.google.protobuf.Any"T\n\x0f\x42ulkInterchange\x12\t\n\x01t\x18\x01 \x01(\t\x12\x0c\n\x04uids\x18\x02 \x03(\x03\x12(\n\x01\x64\x18\x03 \x03(\x0b\x32\x1d.derailed.gateway.Interchange"\x17\n\tGuildInfo\x12\n\n\x02id\x18\x01 \x01(\x03"5\n\rGuildMetadata\x12\x11\n\tavailable\x18\x01 \x01(\x08\x12\x11\n\tpresences\x18\x02 \x01(\x05\x32\xb2\x02\n\x05Guild\x12G\n\x0e\x64ispatch_guild\x12\x1d.derailed.gateway.Interchange\x1a\x16.google.protobuf.Empty\x12\x46\n\rdispatch_user\x12\x1d.derailed.gateway.Interchange\x1a\x16.google.protobuf.Empty\x12J\n\rdispatch_bulk\x12!.derailed.gateway.BulkInterchange\x1a\x16.google.protobuf.Empty\x12L\n\x0cget_metadata\x12\x1b.derailed.gateway.GuildInfo\x1a\x1f.derailed.gateway.GuildMetadatab\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "gateway_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _INTERCHANGE._serialized_start = 91
    _INTERCHANGE._serialized_end = 160
    _BULKINTERCHANGE._serialized_start = 162
    _BULKINTERCHANGE._serialized_end = 246
    _GUILDINFO._serialized_start = 248
    _GUILDINFO._serialized_end = 271
    _GUILDMETADATA._serialized_start = 273
    _GUILDMETADATA._serialized_end = 326
    _GUILD._serialized_start = 329
    _GUILD._serialized_end = 635
# @@protoc_insertion_point(module_scope)
