[tool.ruff]
exclude = [
    '.git',
    '.idea',
    '.vs',
    '.vscode',
    '__pycache__',
    'docs',
    'build',
    'dist',
    'venv',
    'breaking',
    '.github',
    'tests-dev',
]
ignore = []
line-length = 110
select = [
    'D104',
    'D105',
    'D106',
    'D201',
    'D202',
    'D204',
    'D205',
    'D206',
    'D207',
    'D208',
    'D209',
    'D210',
    'D211',
    'D214',
    'D215',
    'D300',
    'D400',
    'D403',
    'D404',
    'D405',
    'D406',
    'D407',
    'D408',
    'D409',
    'D410',
    'D411',
    'D412',
    'D414',
    'D418',
    'D419',
    'E',
    'F',
    'W',
]
fix = true

[tool.ruff.per-file-ignores]
"__init__.py" = [
    'F401',
    'F403',
]

[tool.ruff.flake8-quotes]
inline-quotes = "single"
multiline-quotes = "single"
docstring-quotes = "double"