name: Build Gateway
on:
  push:
    branches:
      - main
      - staging
      - trying
  pull_request:

jobs:
  build-gateway:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd gateway
      - name: Build Gateway
        run: docker build .
